[package]
name = "lambda"
version = "0.1.0"
authors = ["andy baizon <dev@baizon.uk>"]
edition = "2021"

[dependencies]
lambda_runtime = "0.6.0"
serde = "1.0.143"
serde_json = "1.0.83"
tokio = "1.20.1"
